// Map of full names to probable country/nationality codes
// Used to disambiguate ethnicity search (e.g. distinguish Vietnamese "Ho" from Chinese "Ho")
export const nameOriginMap = {
    // --- Vietnamese (vn) ---
    "Bach Le": "vn",
    "Dung D. Le": "vn",
    "Hien Quoc Ngo": "vn",
    "Hung Quang Ngo": "vn",
    "Phu Dung Le": "vn",
    "Thai Le": "vn",
    "Tuan M. V. Le": "vn",
    "Van Bang Le": "vn",
    "Xuan-Bach Ngo": "vn",
    "Thang D. Bui": "vn",
    "Thang Duc Bui": "vn",
    "Thanh Trung Huynh": "vn",
    "Thanh-Toan Do": "vn",
    "Tien D. Bui": "vn",
    "Tien Dai Bui": "vn",
    "Trung Q. Duong": "vn",
    "Trung Quang Duong": "vn",
    "Trung Thanh Huynh": "vn",
    "Long Hoang Dang": "vn",

    // --- Chinese / Taiwanese / HK / SG (cn, tw, hk, sg) ---
    "Chien-Ju Ho": "tw",
    "Chong Wah Ngo": "cn", // HK/Malaysia
    "Chong-Wah Ngo": "cn",
    "Edmond S. L. Ho": "hk",
    "Qirong Ho": "cn", // SG
    "Tsung-Yi Ho": "tw",
    "Wei Le": "cn",
    "Che-Rung Lee": "tw",
    "Chia-Yen Lee": "tw",
    "Chiang Lee": "tw",
    "Chin Ho Lee": "cn",
    "Jenq Kuen Lee": "tw",
    "Jenq-Kuen Lee": "tw",
    "Jimmy H. M. Lee": "hk",
    "Jimmy Ho-Man Lee": "hk",
    "Jong-Seok Lee": "kr", // Actually Korean
    "Kun-Pyo Lee": "kr",  // Actually Korean
    "Lin-shan Lee": "tw",
    "Mong-Li Lee": "sg",
    "Patrick P. C. Lee": "hk",
    "Patrick Pak-Ching Lee": "hk",
    "Ruby B. Lee": "us", // US/Chinese
    "Sang-goo Lee": "kr",
    "Tai Sing Lee": "cn",
    "Tong-Yee Lee": "tw",
    "Victor C. S. Lee": "hk",
    "Victor Chung Sing Lee": "hk",
    "Vincent C. S. Lee": "au", // Australian/Asian
    "Vincent Cheng-Siong Lee": "au",
    "Wang-Chien Lee": "tw",
    "Wee Sun Lee": "sg",
    "Wenke Lee": "cn",
    "Yi-Chieh Lee": "tw",
    "Yin Tat Lee": "hk",

    // --- Korean (kr) ---
    "Ayoung Kim": "kr",
    "B. G. Kim": "kr",
    "Baek-Young Choi": "kr",
    "Beom-Joon Kim": "kr",
    "Beomjoon Kim": "kr",
    "Bo-yong Park": "kr",
    "Bongshin Lee": "kr",
    "Bryan S. Kim": "kr", // Korean-American usually
    "Bryan Suk Joon Kim": "kr",
    "Bu-Sung Lee": "sg", // Singaporean
    "Byoungyoung Lee": "kr",
    "Byron Choi": "hk", // HK
    "Byung Guk Kim": "kr",
    "Byung Seub Lee": "kr",
    "Byung-Guk Kim": "kr",
    "Byungjoo Lee": "kr",
    "Chan-Mo Park": "kr",
    "Chang-Gun Lee": "kr",
    "Chang-Hun Kim": "kr",
    "Chang-Wook Kim": "kr",
    "Changhee Lee": "kr",
    "Changhun Kim": "kr",
    "Changhyun Choi": "kr",
    "Changick Kim": "kr",
    "Changsu Kim": "kr",
    "Chanik Park": "kr",
    "Cheeha Kim": "kr",
    "Chong-kwon Kim": "kr",
    "Chong-Kwon Kim": "kr",
    "Chongkwon Kim": "kr",
    "Choonhwa Lee": "kr",
    "Chul-Ho Lee": "kr",
    "Chun-Yi Lee": "tw", // Taiwanese
    "Chung Hwan Kim": "kr",
    "Chung-Hwan Kim": "kr",
    "Chunghwan Kim": "kr",
    "Dae-Kyoo Kim": "kr",
    "Daehyeok Kim": "kr",
    "Daehyung Park": "kr",
    "Dong Seong Kim": "kr",
    "Dong-Guk Shin": "kr",
    "Dong-Yoon Lee": "kr",
    "Dongkun Shin": "kr",
    "Dongkyun Kim": "kr",
    "Dongman Lee": "kr",
    "Dongwan Shin": "kr",
    "Dongyoon Lee": "kr",
    "Doowon Kim": "kr",
    "Duan-Shin Lee": "tw", // Taiwanese
    "Edward Choi": "kr", // Korean-American
    "Euiwoong Lee": "kr",
    "Eun Kyong Shin": "kr",
    "Eunbyung Park": "kr",
    "Eunhyeok Park": "kr",
    "Eunil Park": "kr",
    "Eunjoo Lee": "kr",
    "Eunsol Choi": "kr",
    "Frank Chongwoo Park": "kr",
    "Gary Geunbae Lee": "kr",
    "Geehyuk Lee": "kr",
    "Gene Louis Kim": "kr",
    "Gerard J. Kim": "kr",
    "Gerard Jounghyun Kim": "kr",
    "Geunbae Lee": "kr",
    "Gi-Soo Kim": "kr",
    "Gim Hee Lee": "kr",
    "Gunhee Kim": "kr",
    "Gunwoong Park": "kr",
    "Gwangsun Kim": "kr",
    "Gyeong-Moon Park": "kr",
    "Gyungho Lee": "kr",
    "H. Jin Kim": "kr",
    "Hae-Seung Lee": "kr",
    "Haesun Park": "kr",
    "Harlin Lee": "kr",
    "Heejin Park": "kr",
    "Heejo Lee": "kr",
    "Heewook Lee": "kr",
    "Heung-Kyu Lee": "kr",
    "Ho Jin Choi": "kr",
    "Hogun Park": "kr",
    "Hokeun Kim": "kr",
    "Hun-Seok Kim": "kr",
    "Huy Kang Kim": "vn", // Vietnamese (Huy)
    "Huy T. Vo": "vn", // Vietnamese
    "Hwangnam Kim": "kr",
    "Hyeoncheol Kim": "kr",
    "Hyeong-Ah Choi": "kr",
    "Hyesoon Kim": "kr",
    "Hyeyoung Park": "kr",
    "Hyogon Kim": "kr",
    "Hyojoon Kim": "kr",
    "Hyoun Jin Kim": "kr",
    "Hyoungshick Kim": "kr",
    "Hyun Soo Park": "kr",
    "Hyung-Sin Kim": "kr",
    "Hyunjin Park": "kr",
    "Hyunsook Do": "kr",
    "Hyunwoo J. Kim": "kr",
    "Hyunwoo Park": "kr",
    "I-Ting Angelina Lee": "tw", // Taiwanese
    "Il Kon Kim": "kr",
    "In Kee Kim": "kr",
    "In-Kwon Lee": "kr",
    "Inhwan Lee": "kr",
    "Insik Shin": "kr",
    "Isaac H. Kim": "kr",
    "J. H. M. Lee": "hk", // Likely Jimmy Lee (HK)
    "Jae Joon Kim": "kr",
    "Jae W. Lee": "kr",
    "Jae Young Do": "kr",
    "Jae-il Kim": "kr",
    "Jae-Soo Kim": "kr",
    "Jaeho Lee": "kr",
    "Jaeil Kim": "kr",
    "Jaejin Lee": "kr",
    "Jaejoon Kim": "kr",
    "Jaesik Choi": "kr",
    "Jaesik Park": "kr",
    "Jaewoo Lee": "kr",
    "Jaeyoung Do": "kr",
    "Jang Hyun Kim": "kr",
    "Jang-Hyun Kim": "kr",
    "Jangwoo Kim": "kr",
    "Jay Yoon Lee": "kr",
    "Jay-Yoon Lee": "kr",
    "Jee W. Choi": "kr",
    "Jeeeun Kim": "kr",
    "Jehee Lee": "kr",
    "Jennifer G. Kim": "kr",
    "Jeong Joon Park": "kr",
    "Jeong-Geun Kim": "kr",
    "Jeonghong Kim": "kr",
    "Ji Hwan Park": "kr",
    "Ji-Hyun Lee": "kr",
    "Ji-Yong Shin": "kr",
    "Jieung Kim": "kr",
    "Jihyeok Park": "kr",
    "Jin Ryong Kim": "kr",
    "Jin Young Choi": "kr",
    "Jin-Ho Lee": "kr",
    "Jin-Young Choi": "kr",
    "Jinah Park": "kr",
    "Jinho D. Choi": "kr",
    "Jinho Lee": "kr",
    "Jinman Kim": "kr",
    "Jinseek Choi": "kr",
    "Jinsub Kim": "kr",
    "Jinwoo Shin": "kr",
    "Jisu Kim": "kr",
    "Jong Cheol Park": "kr",
    "Jong Taek Lee": "kr",
    "Jong-eun Lee": "kr",
    "Jong-Hoon Kim": "kr",
    "Jong-Hwan Lee": "kr",
    "Jong-Hyeok Lee": "kr",
    "Jong-Hyeok Park": "kr",
    "Jong-Hyun Choi": "kr",
    "Jong-Il Park": "kr",
    "Jong-Kook Kim": "kr",
    "Jong-Seok Lee": "kr",
    "Jongeun Choi": "kr",
    "Jongeun Lee": "kr",
    "Jonghyeok Park": "kr",
    "Jonghyuk Kim": "kr",
    "Jonghyun Choi": "kr",
    "Jongok Kim": "kr",
    "Jongouk Choi": "kr",
    "Jongse Park": "kr",
    "Jongsun Park": "kr",
    "Jongwuk Lee": "kr",
    "Joongheon Kim": "kr",
    "Joonseok Lee": "kr",
    "Jooyong Lee": "kr",
    "Jun Won Choi": "kr",
    "Jun-Won Choi": "kr",
    "Jung-Eun Kim": "kr",
    "Junghee Lee": "kr",
    "Jungheum Park": "kr",
    "Jungrae Kim": "kr",
    "Jungyong Kim": "kr",
    "Junwon Choi": "kr",
    "Juseop Lee": "kr",
    "Juw Won Park": "kr",
    "Kahyun Choi": "kr",
    "Kang G. Shin": "kr",
    "Kang-Min Kim": "kr",
    "Kangsoo Kim": "kr",
    "Kee-Eung Kim": "kr",
    "Key-Sun Choi": "kr",
    "Kihong Park": "kr",
    "Kijung Shin": "kr",
    "Kimin Lee": "kr",
    "Kisung Lee": "kr",
    "Kiyoung Choi": "kr",
    "Kookjin Lee": "kr",
    "Ku-Jin Kim": "kr",
    "Kun-Pyo Lee": "kr",
    "Kunsoo Park": "kr",
    "Kwang In Kim": "kr",
    "Kwangjo Kim": "kr",
    "Kwangtaek Kim": "kr",
    "Kwanguk Kim": "kr",
    "Kyogu Lee": "kr",
    "Kyong Hoon Kim": "kr",
    "Kyong-Ho Lee": "kr",
    "Kyoung Mu Lee": "kr",
    "KyoungSoo Park": "kr",
    "Kyoungwoo Lee": "kr",
    "Kyu Hyung Lee": "kr",
    "Kyu Min Lee": "kr",
    "Kyumin Lee": "kr",
    "Kyunghan Lee": "kr",
    "Kyungho Lee": "kr",
    "Kyungtae Kim": "kr",
    "Lok-won Kim": "kr",
    "Mansu Kim": "kr",
    "Mijung Kim": "kr",
    "Mijung Park": "kr",
    "Min C. Shin": "kr",
    "Min Hun Lee": "kr",
    "Min Kyung Lee": "kr",
    "Min-Hyung Choi": "kr",
    "Ming-Sui Lee": "tw", // Taiwanese
    "Minje Kim": "kr",
    "Minjeong Kim": "kr",
    "Minji Lee": "kr",
    "Minsung Kim": "kr",
    "Minwoo Jake Lee": "kr",
    "Miran Kim": "kr",
    "Miryung Kim": "kr",
    "Moonzoo Kim": "kr",
    "Myoung Ho Kim": "kr",
    "Myung J. Lee": "kr",
    "Myung Jong Lee": "kr",
    "Myung-Soo Kim": "kr",
    "Myungchul Kim": "kr",
    "Myungsuk Kim": "kr",
    "Najoung Kim": "kr",
    "Nam Sung Kim": "kr",
    "Nam Wook Kim": "kr",
    "Namhoon Lee": "kr",
    "Namwook Kim": "kr",
    "Nohpill Park": "kr",
    "Noseong Park": "kr",
    "O-Joun Lee": "kr",
    "Sang-goo Lee": "kr",
    "Sang-Goo Lee": "kr",
    "Sang-hyo Park": "kr",
    "Sang-Wook Kim": "kr",
    "Sanghack Lee": "kr",
    "Sangwook Kim": "kr",
    "Seo Jin Park": "kr",
    "Seokki Lee": "kr",
    "Seon Joo Kim": "kr",
    "Seon Wook Kim": "kr",
    "Seong-Tae Kim": "kr",
    "Seong-Whan Lee": "kr",
    "Seongjun Park": "kr",
    "Seulbae Kim": "kr",
    "Seung-Hee Lee": "kr",
    "Seung-Jong Park": "kr",
    "Seungbae Kim": "kr",
    "Seunggeun Lee": "kr",
    "Seunghee Shin": "kr",
    "Seungjin Choi": "kr",
    "Seungjoo Kim": "kr",
    "Seungmoon Choi": "kr",
    "Seungryong Kim": "kr",
    "Seyoung Kim": "kr",
    "Seyoung Park": "kr",
    "Shin-Dug Kim": "kr",
    "Shin-Jie Lee": "tw", // Taiwanese
    "Sihyung Lee": "kr",
    "Song Min Kim": "kr",
    "Soontae Kim": "kr",
    "Stefan Lee": "us", // Likely US
    "Stephen Lee": "us",
    "Su-In Lee": "kr",
    "Sukyoung Lee": "kr",
    "SuKyoung Lee": "kr",
    "Sun Kim": "kr",
    "Sung-Hee Lee": "kr",
    "Sung-Ho Kim": "kr",
    "Sung-Ju Lee": "kr",
    "Sunghee Choi": "kr",
    "Sunghoon Ivan Lee": "kr",
    "Sungjoon Choi": "kr",
    "Sungkee Lee": "kr",
    "Sungwoo Park": "kr",
    "Sungwoong Kim": "kr",
    "Sunjae Lee": "kr",
    "Sunoo Park": "kr",
    "Sunyoung Kim": "kr",
    "Taegyu Kim": "kr",
    "Taehwan Kim": "kr",
    "Taejoon Park": "kr",
    "Taesoo Kim": "kr",
    "Taesup Kim": "kr",
    "Won Hwa Kim": "kr",
    "Won Suk Lee": "kr",
    "Won-Gyu Lee": "kr",
    "Won-Sook Lee": "kr",
    "Won-Suk Choi": "kr",
    "Won-Suk Lee": "kr",
    "WonGyu Lee": "kr",
    "Wonsook Lee": "kr",
    "WonSook Lee": "kr",
    "Wonsuk Choi": "kr",
    "Woo Jin Lee": "kr",
    "Yanggon Kim": "kr",
    "Yanghee Choi": "kr",
    "Yeong-Gil Shin": "kr",
    "Yong Jae Lee": "kr",
    "Yong Suk Choi": "kr",
    "Yong-Lae Park": "kr",
    "Yongdae Kim": "kr",
    "Yongdai Kim": "kr",
    "Yongjoo Park": "kr",
    "Yongju Lee": "kr",
    "Yongsu Park": "kr",
    "Yongsuk Choi": "kr",
    "Yongtae Kim": "kr",
    "Yoohwan Kim": "kr",
    "Yoon Kim": "kr",
    "Yoon-Joon Lee": "kr",
    "Youjin Shin": "kr",
    "Young Choon Lee": "kr",
    "Young Geun Kim": "kr",
    "Young Hee Lee": "kr",
    "Young-joo Shin": "kr",
    "Young-ri Choi": "kr",
    "Younggeun Kim": "kr",
    "Youngjoo Shin": "kr",
    "Youngmoon Lee": "kr",
    "Youngsok Kim": "kr",
    "Youngwoon Lee": "kr",
    "Yugyung Lee": "kr",
    "Yunja Choi": "kr",

    // --- Western / Ambiguous Default (us, or non-matching) ---
    "Adam J. Lee": "us",
    "Andrew C. Lee": "us",
    "Ben Lee": "us",
    "Benjamin C. Lee": "us",
    "David T. Lee": "us",
    "David Timothy Lee": "us",
    "Dik Lun Lee": "hk",
    "Edward A. Lee": "us",
    "Edward Ashford Lee": "us",
    "Grant Ho": "us",
    "Joyce C. Ho": "us",
    "Melissa Ho": "us",
    "Melissa R. Ho": "us",
    "Tracey Ho": "us",
    "Troy Lee": "us",
    "Lillian Lee": "us",
    "Luke J. Lee": "us",
    "Mark G. Lee": "us",
    "Martha A. Kim": "us",
    "Martha Mercaldi Kim": "us",
    "Michael E. Shin": "us",
    "Michael Eonsuk Shin": "us",
    "Michael P. Kim": "us",
};
